In [ ]:
#Social_Networks_Ads.csv

**Importing the libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Importing the dataset**

In [ ]:
data=pd.read_csv("https://raw.githubusercontent.com/HariKumarN14/Training-datasets/main/Social_Network_Ads.csv")
data.head()

In [ ]:
data.shape

(400, 5)

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [4]:
data["Purchased"].unique()

array([0, 1])

In [5]:
data["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [6]:
from sklearn import preprocessing
label_encode=preprocessing.LabelEncoder()
data["Gender"]=label_encode.fit_transform(data["Gender"])

In [7]:
data["Gender"].unique()

array([1, 0])

**Splitting the dataset into the Training set and Test set**

In [8]:
x=data[["Gender","Age","EstimatedSalary"]].values
y=data["Purchased"].values
#print(x)
#print(y)

In [9]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=0)

**Feature Scaling**

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)


**Fitting K-NN to the Training set**

In [11]:
from sklearn.neighbors import KNeighborsClassifier

k=2

model=KNeighborsClassifier(n_neighbors=k).fit(x_train,y_train)

**Predicting the Test set results**

In [12]:
predict=model.predict(x_test)
predict

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [13]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, model.predict(x_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, predict))

Train set Accuracy:  0.921875
Test set Accuracy:  0.925


**Making the Confusion Matrix**

In [14]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, predict))


[[55  3]
 [ 3 19]]


In [15]:
print(classification_report(y_test, predict))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95        58
           1       0.86      0.86      0.86        22

    accuracy                           0.93        80
   macro avg       0.91      0.91      0.91        80
weighted avg       0.93      0.93      0.93        80

